### ISSUE TITLE
Custom route sessions expire after few seconds

### ISSUE THREAD

**Issue by sukumar-v** [Shopify/shopify-api-node#185]
# Issue summary

I had created a sample app using the shopify cli tool (`shopify create`) and I wanted to add additional routes to the existing app. I have created a route called `/api/orders` which returns a list of all the orders.

`server.js`
```javascript
router.post(
    "/graphql",
    verifyRequest({ returnHeader: true }),
    async (ctx, next) => {
      await Shopify.Utils.graphqlProxy(ctx.req, ctx.res);
    }
  );

router.get("/api/orders", verifyRequest(), async (ctx) => {
    console.log(ACTIVE_SHOPIFY_SHOPS);
    const session = await Shopify.Utils.loadCurrentSession(ctx.req, ctx.res);
    const client = new Shopify.Clients.Graphql(
      session.shop,
      session.accessToken
    );
    // console.log("Loaded token: ", session.accessToken)
    // console.log("cookies: ", ctx.cookies.get('accessToken'))
    ctx.body = await api_orders(client, ctx.params, ctx.query);  // returns JSON string  });
```
After starting the server (`shopify serve`), I go ahead and authenticate myself by opening the auth URL (`https://<ngrock_url>/auth?shop=shopname.myshopify.com`) in my browser. 

Once I'm done with that I can get the orders by opening the defined route in my browser (`https://<ngrock_url>/api/orders`). However when I open the url again after a few seconds, it redirects me to a different unrecognized url (`https://admin/oauth/authorize?client_id=e74e84f43b273631f1asdfccbd1d6607f2bc&scope=read_orders&redirect_uri=https%3A%2F%2F3960a5286b424.ngrok.io%2Fauth%2Fcallback&state=233468616505697&grant_options%5B%5D=per-user`)

## Expected behavior

`https://<ngrock_url>/api/orders` url continues to return a list of orders even after some time has passed.

## Actual behavior

Opening the url after some time redirects to an unknown page or returns `TypeError: Cannot read property 'map' of undefined`.

```bash
TypeError: Cannot read property 'map' of undefined
       at new AuthScopes (/home/gts/Projects/personal/shopify/sample_app/node_modules/@shopify/shopify-api/dist/auth/scopes/index.js:14:35)
       at AuthScopes.equals (/home/gts/Projects/personal/shopify/sample_app/node_modules/@shopify/shopify-api/dist/auth/scopes/index.js:38:21)
       at /home/gts/Projects/personal/shopify/sample_app/node_modules/@shopify/koa-shopify-auth/dist/src/verify-request/verify-token.js:23:79
       at step (/home/gts/Projects/personal/shopify/sample_app/node_modules/tslib/tslib.js:133:27)
       at Object.next (/home/gts/Projects/personal/shopify/sample_app/node_modules/tslib/tslib.js:114:57)
       at fulfilled (/home/gts/Projects/personal/shopify/sample_app/node_modules/tslib/tslib.js:104:62)
       at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Steps to reproduce the problem

1. Create node app using shopify cli (`shopify create node`)
2. Add `/api/orders` route in `server.js` and add `read_orders` scope to `.env`
3. Open the defined route in browser after authenticating your app. 
4. Open the same url again after a minute.

## Checklist
- [x] Tried with offline tokens which returns the second error: `TypeError: Cannot read property 'map' of undefined` in `auth/scopes`

**Comment by thivatm** [comment]
I tried the same approach to create a custom route for subscriptions and inside the route I was making graphql request using the access token from the current session. It always returns an 401 response with the below message

[API] Invalid API key or access token (unrecognized login or wrong password)

Is this because the session is expiring?
