### ISSUE TITLE
Pass isOnline flag in docs for NodeJS

### ISSUE THREAD

**Issue by maxfrigge** [Shopify/shopify-api-node#198]
## Overview/summary

The [docs to begin OAuth](https://github.com/Shopify/shopify-node-api/blob/main/docs/usage/oauth.md#add-a-route-to-start-oauth) don't include the `isOnline` argument in the NodeJS code snippet. It is set in the Express example though and basically forces the Cookie to immediately expire when not set - i.e. breaking the OAuth flow when following the vanilla NodeJS docs. I would suggest using online auth in the NodeJS code as well.

<img width="1032" alt="Screen Shot 2021-06-13 at 12 36 37" src="https://user-images.githubusercontent.com/11060313/121804184-66890e80-cc45-11eb-9654-8f6a08928fd6.png">

## Motivation

I spent too much time reverse engineering why the vanilla NodeJS code wasn't working. This small adjustment in your docs could save others the time to figure it out the hard way.

...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [ ] I have described this enhancement in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
That is a great suggestion @maxfrigge, thank you! We'll add that to the documentation to prevent others from running into the same issue.

**Comment by mkevinosullivan** [comment]
Closing this issue as docs have since been updated.
