### ISSUE TITLE
How to get the shop and merchant detail?

### ISSUE THREAD

**Issue by zilehuda** [Shopify/shopify-api-node#236]
How to get shop and merchant detail (including name, email) using Shopify node API?

In shopify ruby API (https://github.com/Shopify/shopify_api), we can access it like
`ShopifyAPI::Shop.current`
`ShopifyAPI::Shop.current.email`

what is the alternate of this in Shopify node API?

**Comment by michaelnwani** [comment]
@zilehuda 👋 Hi! Did you happen to figure it out? I'm sure this would help many developers 😁
