### ISSUE TITLE
ApiVersion.January22

### ISSUE THREAD

**Issue by zookcorp** [Shopify/shopify-api-node#289]
# Issue summary
Im using: "@shopify/shopify-api": "^2.0.0"

Please re-publish on npmjs, ApiVersion.January22 is not found

**Comment by tolgap** [comment]
As a workaround you can force this using type casting:

```ts
Shopify.Context.initialize({
  // ...
  API_VERSION: "2022-01" as ApiVersion,
});
```

**Comment by WeikunYe** [comment]
What about JavaScript? Type casting is only for typescript right?

**Comment by WeikunYe** [comment]
> As a workaround you can force this using type casting:
> 
> ```ts
> Shopify.Context.initialize({
>   // ...
>   API_VERSION: "2022-01" as ApiVersion,
> });
> ```

I try ``API_VERSION: "2022-01"`` in JavaScript but it's not working

**Comment by Arias-xss** [comment]
Hi!, I have the same problem, but my project was develop all in js, how can I use the January version without make "as ApiVersion"

**Comment by bishpls** [comment]
@Arias-xss Just remove the TypeScript casting and pass in "2022-01" as a string

```
Shopify.Context.initialize({
  // ...
  API_VERSION: "2022-01",
});
```

**Comment by PaulvdDool** [comment]
`ApiVersion.January22` is now part of version 2.1.0 but `ApiVersion.April22` is missing even though it's defined in the ApiVersion enum in the base-types file.
https://github.com/Shopify/shopify-node-api/blob/main/src/base-types.ts

Seems to me the NPM package is not updated properly?
