### ISSUE TITLE
I have a problem with " Cannot complete OAuth process. Could not find an OAuth cookie for shop url"

### ISSUE THREAD

**Issue by ClairCc** [Shopify/shopify-api-node#293]
I was following the shopify tutorial
https://www.youtube.com/watch?v=oKGR9RVCUDs
And I got the following error when I wanted to go to the start of my application

`
  const express = require('express');
  const dotenv = require('dotenv');
  const { Shopify } = require('@shopify/shopify-api');
  
  dotenv.config();
  const host = 'localhost';
  const port = 3000;
  
  const { SHOPIFY_API_KEY, SHOPIFY_API_SECRET, SHOPIFY_API_SCOPES, HOST } =
      process.env;
  const shops = {};
  
  Shopify.Context.initialize({
      API_KEY: SHOPIFY_API_KEY,
      API_SECRET_KEY: SHOPIFY_API_SECRET,
      SCOPES: SHOPIFY_API_SCOPES,
      HOST_NAME: HOST,
      IS_EMBEDDED_APP: true,
  });
  
  const app = express();
  
  app.get('/', (req, res) => {
      if (typeof shops[req.params.shop] !== 'undefined') {
          res.send('Hello, world');
      } else {
          res.redirect(`/auth?shop=${req.query.shop}`);
      }
  });
  
  app.get('/auth', async (req, res) => {
      const authRoute = await Shopify.Auth.beginAuth(
          req,
          res,
          req.query.shop,
          '/auth/callback',
          false
      );
      res.redirect(authRoute);
  });
  
  app.get('/auth/callback', async (req, res) => {
      const shopSession = await Shopify.Auth.validateAuthCallback(
          req,
          res,
          req.query
      );
      console.log(shopSession);
  
      shops[shopSession.shop] = shopSession;
      console.log(shops);
      res.redirect(`https://${shopSession.shop}/admin/apps/payments-14`);
  });
  
  app.listen(port, () => {
      console.log(`Server runing at https://${host}:${port}`);
  });
`

**Comment by lukeclifton** [comment]
I was hitting the same issue, until i realised that i was starting the auth flow using the `localhost:3000` URL and then the auth callback route was hitting my public `ngrok` URL.

You need to start and end the auth flow on the same URL for the oAuth cookie to be set and read correctly on the same domain.

**Comment by lukeclifton** [comment]
@johnciprian Are you using ngrok for the oAuth redirects?

**Comment by johnciprian** [comment]
@lukeclifton That's exactly what's happening to me. This just started happening. When I run npm run dev it use to give me a URL pointing to ngrok. Now the same command only points to local host. I wonder what I'm doing wrong. 🤔
