### ISSUE TITLE
I have questions about the CLI ?

### ISSUE THREAD

**Issue by ClairCc** [Shopify/shopify-api-node#296]
I've been using the Shopify cli and I haven't seen the "routes" where I can do the requests, be they Post , Get , put etc.
I've spent a lot of time analyzing the code and I can't create a get or a post, is there a tutorial that can help me with this

**Comment by redochka** [comment]
@ClairCc I stopped using the shopify-cli generated app. Just published a working example using nextjs. If you know nextjs you can do whatever you want. https://github.com/redochka/nextjs-shopify-app-no-custom-server
Give it a try
