### ISSUE TITLE
Cannot complete OAuth process. Could not find an OAuth cookie for shop url:

### ISSUE THREAD

**Issue by mkamalkayani** [Shopify/shopify-api-node#299]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@shopify/shopify-api@2.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js b/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js
index 719f989..544abb6 100644
--- a/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js
+++ b/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js
@@ -52,7 +52,7 @@ var ShopifyOAuth = {
                         cookies.set(ShopifyOAuth.SESSION_COOKIE_NAME, session.id, {
                             signed: true,
                             expires: new Date(Date.now() + 60000),
-                            sameSite: 'lax',
+                            sameSite: 'none',
                             secure: true,
                         });
                         query = {
```

I get this error in the oauth callback for the offline accessToken. I am doing the oauth in the top level window still I get this error. Am I doing something incorrectly or is it a bug in the library?

**Comment by gayanhewa** [comment]
Does anyone know where I can find more about why we need a top-level window for auth to complete? It's not very clear as to why ?

**Comment by mkamalkayani** [comment]
I am also confused about it in general. However, in this particular case, the library is setting a cookie vie a set-cookie header and if the window is not top level then the browser rejects the cookie because of sameSite restrictions.

**Comment by ali-faiz-brainx** [comment]
I'm facing the same issue can anyOne find a solution for this? My app is on Shopify CLI2.0
