### ISSUE TITLE
Multiple instances of Shopify Context

### ISSUE THREAD

**Issue by ozzyonfire** [Shopify/shopify-api-node#309]
## Overview
I'm coming from my own custom implementation of OAuth and handling app access through a node (actually NextJs) backend. This library looks great! But I'd like to set up multiple Shopify Apps that use the same backend server for OAuth. 

It looks like this package is meant to use the Singleton pattern, so initializing context upfront, and then accessing it everywhere else. 

Is there a way I can set up multiple instances of the package so different Express routes can handle different Shopify apps?

i.e.

```javascript
const myApp = new Shopify({ api_key, api_secret_key, ...etc });
const myApp2 = new Shopify({ api_key2, api_secret_key2, ...etc });

app.get('/my-app/auth/callback', async (req, res) => {
  const session = await myApp.Auth.validateAuthCallback(
    req,
    res,
    req.query as unknown as AuthQuery,
  );
  console.log(session.accessToken);
  return res.redirect(`/?host=${req.query.host}&shop=${req.query.shop}`); // wherever you want your user to end up after OAuth completes
});

app.get('/my-app-2/auth/callback', async (req, res) => {
  const session = await myApp2.Auth.validateAuthCallback(
    req,
    res,
    req.query as unknown as AuthQuery,
  );
  console.log(session.accessToken);
  return res.redirect(`/?host=${req.query.host}&shop=${req.query.shop}`); // wherever you want your user to end up after OAuth completes
});
```

**Comment by ToyboxZach** [comment]
Its pretty hacky, but I was able to do it with this package by setting

Shopify.Context.API_KEY
Shopify.Context.API_SECRET_KEY
and 
Shopify.Context.SCOPES
Before calling the relevant auth functions

And for offline token, just skipping the Shopify.Auth.beginAuth and storing the token explicitly so I can find it

and call Shopify.Clients.Rest(shop,token) directly.

**Comment by v-octal** [comment]
@paulomarg Any updates on this?

**Comment by mkevinosullivan** [comment]
This will now be possible with the upcoming version 6 of the API library.  There's a release candidate currently available for download (`v6.0.0-rc1`).

**Comment by v-octal** [comment]
@mkevinosullivan Is `v6.0.0-rc1` released?
If it is, Can you point me to the documentation for handling multiple shop context on the same server?

**Comment by mkevinosullivan** [comment]
@avtans-kumar-shipsy Sorry I didn't see this comment until now ... with v6 you can create two different instances as follows:
```js
const shopify1 = shopifyApi({config for 1});
const shopify2 = shopifyApi({config for 2});
```
