### ISSUE TITLE
REST client GET request logs "API Deprecation Notice" warning

### ISSUE THREAD

**Issue by NathanScheele** [Shopify/shopify-api-node#315]
# Issue summary

I have a custom Shopify app, which makes calls to various REST API endpoints. Regardless of which API version I use, an API Deprecation Notice is logged to the console.

## Expected behavior

According to [Shopify's versioning documentation](https://shopify.dev/api/usage/versioning#rest-api-deprecation-practices), 

> If individual properties on a resource are deprecated, then GET requests to that resource don't return the deprecation header in the response.

I would expect no warning to be logged when sending a GET request to the orders endpoint.

## Actual behavior

The following warning is logged in the console:

```
API Deprecation Notice: {
  message: 'https://shopify.dev/changelog/property-deprecations-in-the-rest-admin-api-order-resource',
  path: 'https://my-shopify-store.myshopify.com/admin/api/unstable/orders/123456789.json?fields=id%2Cname%2Ctags%2Cline_items%2Cshipping_address%2Cshipping_lines%2Ccreated_at%2Cemail%2Ccancelled_at'
}
```
## Steps to reproduce the problem

```
const {Shopify} = require("@shopify/shopify-api");

const shopifyRestClient = new Shopify.Clients.Rest("my-shopify-store.myshopify.com", "shpat_xxx");

shopifyRestClient.get({ path: 'orders/123456789' });
```
---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by EduardoMateos** [comment]
Is there any way to hide it now? I am filling the logs of that warning.

**Comment by Trimakas** [comment]
still happening, when all I return are the `shipping_lines`

**Comment by tt-abetemadi** [comment]
I also, get this warning when trying to create an order with REST Admin API

**Comment by yanisforcedtocode** [comment]
The API deprecation notice works this way:
`<html>
<body>


const deprecationReason = getHeader(
--
298 | response.headers,
299 | 'X-Shopify-API-Deprecated-Reason',
300 | );
301 | if (deprecationReason) {
… |  
325 | const stack = new Error().stack;
326 | const message = `API Deprecation Notice ${new Date().toLocaleString()} : ${JSON.stringify(


</body>
</html>`

If the program picks up a 'X-Shopify-API-Deprecated-Reason' header in the REST response, it will log a warning to the console accordingly. I come to realize that the information in this header is not always accurate...

I simply comment out the following line in this file of the module:
lib/clients/http_client/http_client.js
`yield log.warning(message)`

then patch the package:
https://www.npmjs.com/package/patch-package

and enjoy peace

**Comment by indice** [comment]
I also get a warning when I apply for Ordes
