### ISSUE TITLE
How to save the accessToken with CustomSessionStorage?

### ISSUE THREAD

**Issue by charle-connoringold** [Shopify/shopify-api-node#336]
## Overview/summary
First of all, I really like the project and thank you for the work you've put into this!
I just have one question which I can't seem to find the answer to anywhere in the docs and it's really bugging me. 
So I've set up auth routes and custom session storage as I've put below (basically identical to the docs).
My question is this, how with the shopify-node-api do I save the session and how do I access it? 
```
Shopify.Context.initialize({
  API_KEY: SHOPIFY_API_KEY,
  API_SECRET_KEY: SHOPIFY_API_SECRET,
  SCOPES: ["read_customers", "write_customers"],
  HOST_NAME: HOST.replace(/https:\/\//, ""),
  IS_EMBEDDED_APP: true,
  ApiVersion: "January22",
  SESSION_STORAGE: new Shopify.Session.CustomSessionStorage(storeCallBack, loadCallBack, deleteCallBack)
})

app.get('/auth/callback', async (req, res) => {
  try {
    const session = await Shopify.Auth.validateAuthCallback(
      req,
      res,
      req.query as unknown as AuthQuery,
    );
    // How do I save you?
    console.log(session.accessToken);
  } catch (error) {
    console.error(error); // in practice these should be handled more gracefully
  }
  return res.redirect(`/?host=${req.query.host}&shop=${req.query.shop}`); // wherever you want your user to end up after OAuth completes
});
```
...

## Motivation

> Struggling to kind the answer in the current docs or anywhere.

**Comment by bishpls** [comment]
validateAuthCallback calls SESSION_STORAGE.storeCallback (or rather, SESSION_STORAGE.storeSession, which then calls storeCallback) under the hood -- so assuming your CustomSessionStorage is implemented properly, it's already being done!

See here: https://github.com/Shopify/shopify-node-api/blob/2527af569d9e5be95848081c086f5cd19cf632d7/src/auth/oauth/oauth.ts#L200

**Comment by bishpls** [comment]
@charle-connoringold 

Yes, but no, but yes, but kind of? 

That's the INTENDED functionality, but it can get a little wacky if you're using offline access token sessions, due to some unresolved issues. 

See here: https://github.com/Shopify/shopify-node-api/pull/272

Long story short: for a standalone (non-embedded) app using offline sessions, loadCurrentSession is currently borked, and loadOfflineSession is not a clean drop-in replacement due to the fact that it doesn't validate the request. I've written up the details here: https://github.com/Shopify/shopify-node-api/pull/199#issuecomment-1021733105

**Comment by sanjay-ios-io** [comment]
Any Fixed on this issue ?

**Comment by charle-connoringold** [comment]
> Any Fixed on this issue ?

I ended up using the new MongoDBSessionStorage session storage:

```
const { API_KEY, API_SECRET_KEY, SCOPES, SHOP, HOST, HOST_SCHEME } = process.env

Shopify.Context.initialize({
  API_KEY,
  API_SECRET_KEY,
  SCOPES: SCOPES.split(','),
  HOST_NAME: HOST.replace(/https?:\/\//, ''),
  HOST_SCHEME,
  IS_EMBEDDED_APP: true,
  API_VERSION: LATEST_API_VERSION, // all supported versions are available, as well as "unstable" and "unversioned"
  SESSION_STORAGE: new Shopify.Session.MongoDBSessionStorage(
    new URL(process.env.DB_HOST),
    process.env.DB_NAME,
  ),
})
```
Which automatically stores the session when validateAuthCallback is called. And then calling loadCurrentSession will load the session for you.

**Comment by charle-connoringold** [comment]
@sanjay-ios-io In my case, it's just an environment variable in a .env file, and the value is apps-testing-connor.myshopify.com

**Comment by sanjay-ios-io** [comment]
@charle-connoringold  Thanks for the answer 
Shop URL i am getting into my code  Dynamically args.shop  this was the my active shop args
 **args.shop ==  mytestingshop.myshopify.com**

`   const session = new Shopify.Utils.loadOfflineSession(args.shop);
    const client = new Shopify.Clients.Graphql(session.shop, session.accessToken); `
    
    Error i am getting  
    `
Error Getting Client side on console 
{
  "message": "Missing access token when creating GraphQL client",
  
}


Server side Error 

@shopify/shopify-api/dist/auth/oauth/oauth.js:207
            var authHeader = request.headers.authorization;
                                             ^

TypeError: Cannot read properties of undefined (reading 'authorization')`
