### ISSUE TITLE
Add type definitions for webhook payloads

### ISSUE THREAD

**Issue by kyle-villeneuve** [Shopify/shopify-api-node#359]
## Overview

Adding in the type definitions of webhook payloads would be immensely helpful, either here or in your documentation somewhere. As far as I know the only payload documentation you offer is a single example payload per topic which is not great when trying to deal with all possible type nuances that can exist.

## Type

- [ ] New feature
- [x] Changes to existing features

## Motivation

As of right now my strategy is to accumulate a reasonable sample size of webhooks in my application's db and use a typegen tool based on the sample data, which does work but it's incredibly tedious to deal with. I imagine you probably have the type definitions in your codebase somewhere and it's just a matter of making it publicly available.

### Area

- [ ] webhooks
- [ ] type definitions

**Comment by FelixTellmann** [comment]
Hey Kyle,

looks like its related to issue [#193](https://github.com/Shopify/shopify-node-api/issues/193). I've added a pull request over the weekend to add types to the Rest & Graphql clients. I've also added a forked package to npm that runs with the types integrated already. You can install `shopify-typed-node-api` and import the required types directly from there.

I.e. a webhook for `orders/updated` could be typed like this:

```ts
import { _Order } from "shopify-typed-node-api/dist/clients/rest/dataTypes";

function handleWebhook(req, res) {
  const bodyBuffer = await getRawBody(req);
  const body = JSON.parse(bodyBuffer.toString());
  const {
    "x-shopify-hmac-sha256": hmac,
    "x-shopify-shop-domain": shop,
    "x-shopify-topic": topic,
  } = headers;

  if (!verifyWebhookHmac(hmac, bodyBuffer)) {
    res.status(401).send("Unauthorized Access");
    return;
  }

  switch (topic) {
    case "orders/updated": {
      const order = body as _Order;

      // do stuff with order and have types...

      return res.status(200).send("success");
    }
  }
}
```
