### ISSUE TITLE
[Feature] Access to webhook id in handlers

### ISSUE THREAD

**Issue by tolgap** [Shopify/shopify-api-node#370]
## Overview

I want to process webhooks in an idempotent way. Shopify provides us with `X-Shopify-Webhook-Id` headers. But these get lost in the webhook process function.

It would be great to have access to the webhook ID in my handlers.

## Type

- [ ] New feature
- [x] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?

I want to process webhooks in an asynchronous way, using background workers. For this, I want to use the webhook ID as the background Job ID.

## Checklist

- [x] I have described this feature request in a way that is actionable (if possible)

**Comment by mariusa** [comment]
not stale

**Comment by jbwyme** [comment]
any updates here?
