### ISSUE TITLE
GraphQL Proxy doesn't offer an option to use offline access token

### ISSUE THREAD

**Issue by gyotov** [Shopify/shopify-api-node#399]
## Issue overview
I was previously working with the `shopify-node-api` library and I was struggling to use `graphqlProxy` utility function with offline access token(loadOfflineSession).

## Suggestion
I suggest, to update the `graphqlProxy` utility function to use either `loadCurrentSession` or `loadOfflineSession` to get the session:

```
const session = await loadCurrentSession(req, res)
await Shopify.Utils.graphqlProxy(session)
```

or

```
const session = await loadOfflineSession(shop)
await Shopify.Utils.graphqlProxy(session)
```

**Comment by bkspace** [comment]
@paulomarg - is there a reason why only online sessions are acceptable in this function? Happy to do a quick PR for this otherwise.

**Comment by mkevinosullivan** [comment]
Online tokens adopt user-based access permission scopes, which are used to determine if the proxied GraphQL request should be completed or not.  Offline access tokens adopt the scopes of the app backend and thus, depending on those scopes, could expose stores using the app to detrimental GQL queries if allowed via the proxy.

Hence, use of offline access tokens is not allowed for the GraphQL proxy.
