### ISSUE TITLE
Add the barcode field in line item of the order resource on Admin rest API

### ISSUE THREAD

**Issue by viraths** [Shopify/shopify-api-node#417]
## Overview/summary
Can you please include `barcode` field on `line_item` object of the order resource on Admin rest API. https://shopify.dev/api/admin-rest/2022-07/resources/order#resource-object
...

## Motivation

> What inspired this enhancement?
We store the products with barcode as the unique key (making a composite key) and it's easier to get the product if we have barcode on the line item object, otherwise we have to query the product by variant id and find the barcode.
...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [x] I have described this enhancement in a way that is actionable (if possible)

**Comment by jobjen02** [comment]
Please add this. It's so simple, but so much more is possible with this. I don't need to make an extra request to the product variant to fetch the barcode anymore..
