### ISSUE TITLE
Document "sessions" in more detail

### ISSUE THREAD

**Issue by richardscarrott** [Shopify/shopify-api-node#428]
## Overview

Both the `node` and `express` ["Set up context" code examples](https://github.com/Shopify/shopify-api-node/blob/main/docs/getting_started.md#set-up-context) vaguely demonstrate the use of an in-memory `ACTIVE_SHOPIFY_SHOPS` object which is in fact copied verbatim by the `@shopify/app` node template. Anybody using this template needs to understand it because the comment implies it's just there for demo purposes:

```ts
// Storing the currently active shops in memory will force them to re-login when your server restarts. You should
// persist this object in your app.
const ACTIVE_SHOPIFY_SHOPS: { [key: string]: string | undefined } = {};

// the rest of the example code goes here

app.get("/", async (req, res) => {
   // This shop hasn't been seen yet, go through OAuth to create a session
  if (ACTIVE_SHOPIFY_SHOPS[SHOP] === undefined) {
     // not logged in, redirect to login
    res.redirect(`/login`);
  } else {
    res.send("Hello world!");
    // Load your app skeleton page with App Bridge, and do something amazing!
    res.end();
  }
});
```

It's not really clear what the purpose of it is vs the "session" managed by `Shopify.Context.SESSION_STORAGE` and I wonder if further documentation could be provided?

I was expecting to see something more like the following, but given the incredible complexity oauth + appbridge bring to the table, I'm quite nervous to run with this without a complete understanding of what's happening:

```ts
 // This shop hasn't been seen yet, go through OAuth to create a session
 const session = await Shopify.Utils.loadCurrentSession(req, res, false);
  if (!session || !Shopify.Context.SCOPES.equals(session.scope)) {
    // not logged in, or requires different scopes, redirect to login
    res.redirect(`/login`);
    return;
  }
  res.send('Hello World!');
```

Another related concern I have is defining exactly what a "session" is in the context of this library as, for _online_ tokens I think it makes sense to think of the thing stored by SESSION _STORAGE as a session because they are tied to a _user_ and they have an expiry.

However, _offline_ tokens live forever and therefore don't really represent a "session" but rather an "install" or "store" or perhaps "merchant".

Sounds like I'm bike shedding the name, but I think determining where and when you store / retrieve these tokens is significantly impacted by what it _represents_.

This is additionally made confusing due to the "double" session record documented here https://github.com/Shopify/shopify-api-node/issues/224 whereby, even for offline tokens, we see a store-level session being written as well as some other uuid session being written.

It'd be good if you could provide further technical documentation on the various sessions, what they represent and their life cycle to help people avoid bad practices.

## Motivation

> What inspired this enhancement?

Reviewing (and not fully understanding) the generated code from `@shopify/app`.

**Comment by kkwteh** [comment]
I had exactly the same question around what the heck this active shopify shops object is for.

It doesn't seem to do much. I don't see this object mentioned anywhere else in their docs. I ripped out all mention of active-shopify-shops and everything seems to work just fine.
