### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `path` from `/Users/xiaoyiwang/Desktop/ADAPROX/MeshHub-RN-Panel/node_modules/@shopify/shopify-api/dist/context.js`: Module `path` does not exist in the Haste module map

### ISSUE THREAD

**Issue by wangxiaoyi168** [Shopify/shopify-api-node#439]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://webkit.org/test-case-reduction/).

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
Insufficient information provided - please provide more detail in terms of app type/framework/what the app is attempting to do when error occurs.
