### ISSUE TITLE
Mismatched data types provided: string and undefined

### ISSUE THREAD

**Issue by amitkumar3211** [Shopify/shopify-api-node#456]
db.js file =>>>>>>>

 import { Session } from "@shopify/shopify-api/dist/auth/session/session.js";
 import  mysql  from "mysql";

var connection = mysql.createConnection({
    host: "localhost",
    user: "root",
    password: "",
    database: "shopify-app"
});

connection.connect();

let domain_id = '';
export var storeCallback = async (session) => {
    try {
        // console.log(session);
        let data = session;
        //console.log(data);

const payload = {...session}
console.log('payload here ');
console.log(payload); 
        data.onlineAccessInfo = JSON.stringify(session.isOnline);
        //console.log(data.onlineAccessInfo);
        if (data.id.indexOf(`${data.shop}`) > -1) {

            domain_id = data.id;
        }

        connection.query(`INSERT INTO shops (shop_url, session_id, domain_id, access_token, state, is_online, online_access_info, scope) VALUES ('${data.shop}','${data.id}','${domain_id}','${session.accessToken}','${data.state}','${data.isOnline}','${data.onlineAccessInfo}','${data.scope}') ON DUPLICATE KEY UPDATE access_token='${data.accessToken}', state='${data.state}', session_id='${data.id}', domain_id='${domain_id}', scope='${data.scope}', online_access_info='${data.onlineAccessInfo}' `, (error, result, fields) => {
            if (error) throw error
            console.log(result);
        })
return true;

    } catch (err) {
        throw new Error(err);
    }

}

// not used yet 
export var loadCallback = async (id) => {
   console.log(`loadcallback id here ${id}`);
    try {
      

        let newsession =  new Session(id);
        console.log(`access token  here ${newsession.accessToken}`);
        let query = new Promise((resolve, rej) => {

            connection.query(`SELECT * FROM shops where session_id = '${id}' OR domain_id = '${id}' LIMIT 1`, (error, result, fields) => {

                if (error) throw error;
                newsession.shop = result[0].shop_url;
                newsession.state = result[0].state;
                newsession.scope = result[0].scope;
                newsession.isOnline = result[0].isOnline == 'true' ? true : false;
                newsession.onlineAccessInfo = result[0].onlineAccessInfo;
                newsession.accessToken = result[0].accessToken;

               // const date = new date();
               // date.setDate(date.getDate() * 1);
            //  console.log(date);
            //     session.expires = date;

                if (session.expires && typeof newsession.expires == 'string') {
                    session.expires = new Date(newsession.expires);
                }

            });
            resolve();

        });

        await query;
       // console.log(session);
        return newsession;

    } catch (err) {
        throw new Error(err);
    }
}
 // not used yet 
 export const deleteCallback = async (id) => {

    try {
        return false;
    } catch (err) {
        throw new Error(err);
    }
}

Index file =>>>>>>>>>>>>

// @ts-check
import { join } from "path";
import fs from "fs";
import express from "express";
import cookieParser from "cookie-parser";
import { Shopify, LATEST_API_VERSION } from "@shopify/shopify-api";

import applyAuthMiddleware from "./middleware/auth.js";
import verifyRequest from "./middleware/verify-request.js";
import { setupGDPRWebHooks } from "./gdpr.js";
import productCreator from "./helpers/product-creator.js";
import { BillingInterval } from "./helpers/ensure-billing.js";
import { AppInstallations } from "./app_installations.js";
import { storeCallback, loadCallback, deleteCallback } from './db/ouths.js';
const USE_ONLINE_TOKENS = false;
const TOP_LEVEL_OAUTH_COOKIE = "shopify_top_level_oauth";

const PORT = parseInt(process.env.BACKEND_PORT || process.env.PORT, 10);

// TODO: There should be provided by env vars
const DEV_INDEX_PATH = `${process.cwd()}/frontend/`;
const PROD_INDEX_PATH = `${process.cwd()}/frontend/dist/`;

const DB_PATH = `${process.cwd()}/database.sqlite`;

Shopify.Context.initialize({
  API_KEY: process.env.SHOPIFY_API_KEY,
  API_SECRET_KEY: process.env.SHOPIFY_API_SECRET,
  SCOPES: process.env.SCOPES.split(","),
  HOST_NAME: process.env.HOST.replace(/https?:\/\//, ""),
  HOST_SCHEME: process.env.HOST.split("://")[0],
  API_VERSION: LATEST_API_VERSION,
  IS_EMBEDDED_APP: true,
  // This should be replaced with your preferred storage strategy
 //SESSION_STORAGE: new Shopify.Session.SQLiteSessionStorage(DB_PATH),
 SESSION_STORAGE: new Shopify.Session.CustomSessionStorage(
  storeCallback,
  loadCallback,
  deleteCallback

 )

});

Shopify.Webhooks.Registry.addHandler("APP_UNINSTALLED", {
  path: "/api/webhooks",
  webhookHandler: async (_topic, shop, _body) => {
    await AppInstallations.delete(shop);
  },
});

// The transactions with Shopify will always be marked as test transactions, unless NODE_ENV is production.
// See the ensureBilling helper to learn more about billing in this template.
const BILLING_SETTINGS = {
  required: false,
  // This is an example configuration that would do a one-time charge for $5 (only USD is currently supported)
  // chargeName: "My Shopify One-Time Charge",
  // amount: 5.0,
  // currencyCode: "USD",
  // interval: BillingInterval.OneTime,
};

// This sets up the mandatory GDPR webhooks. You’ll need to fill in the endpoint
// in the “GDPR mandatory webhooks” section in the “App setup” tab, and customize
// the code when you store customer data.
//
// More details can be found on shopify.dev:
// https://shopify.dev/apps/webhooks/configuration/mandatory-webhooks
setupGDPRWebHooks("/api/webhooks");

// export for test use only
export async function createServer(
  root = process.cwd(),
  isProd = process.env.NODE_ENV === "production",
  billingSettings = BILLING_SETTINGS
) {
  const app = express();
  app.set("top-level-oauth-cookie", TOP_LEVEL_OAUTH_COOKIE);
  app.set("use-online-tokens", USE_ONLINE_TOKENS);

  app.use(cookieParser(Shopify.Context.API_SECRET_KEY));

  applyAuthMiddleware(app, {
    billing: billingSettings,
  });

  // Do not call app.use(express.json()) before processing webhooks with
  // Shopify.Webhooks.Registry.process().
  // See https://github.com/Shopify/shopify-api-node/blob/main/docs/usage/webhooks.md#note-regarding-use-of-body-parsers
  // for more details.
  app.post("/api/webhooks", async (req, res) => {
    try {
      await Shopify.Webhooks.Registry.process(req, res);
      console.log(`Webhook processed, returned status code 200`);
    } catch (e) {
      console.log(`Failed to process webhook: ${e.message}`);
      if (!res.headersSent) {
        res.status(500).send(e.message);
      }
    }
  });

  // All endpoints after this point will require an active session
  app.use(
    "/api/*",
    verifyRequest(app, {
      billing: billingSettings,
    })
  );

  app.get("/api/products/count", async (req, res) => {
    const session = await Shopify.Utils.loadCurrentSession(
      req,
      res,
      app.get("use-online-tokens")
    );
    const { Product } = await import(
      `@shopify/shopify-api/dist/rest-resources/${Shopify.Context.API_VERSION}/index.js`
    );

    const countData = await Product.count({ session });
    res.status(200).send(countData);
  });

  app.get("/api/products/create", async (req, res) => {
    const session = await Shopify.Utils.loadCurrentSession(
      req,
      res,
      app.get("use-online-tokens")
    );
    let status = 200;
    let error = null;

    try {
      await productCreator(session);
    } catch (e) {
      console.log(`Failed to process products/create: ${e.message}`);
      status = 500;
      error = e.message;
    }
    res.status(status).send({ success: status === 200, error });
  });

  // All endpoints after this point will have access to a request.body
  // attribute, as a result of the express.json() middleware
  app.use(express.json());

  app.use((req, res, next) => {
    const shop = Shopify.Utils.sanitizeShop(req.query.shop);
    if (Shopify.Context.IS_EMBEDDED_APP && shop) {
      res.setHeader(
        "Content-Security-Policy",
        `frame-ancestors https://${encodeURIComponent(
          shop
        )} https://admin.shopify.com;`
      );
    } else {
      res.setHeader("Content-Security-Policy", `frame-ancestors 'none';`);
    }
    next();
  });

  if (isProd) {
    const compression = await import("compression").then(
      ({ default: fn }) => fn
    );
    const serveStatic = await import("serve-static").then(
      ({ default: fn }) => fn
    );
    app.use(compression());
    app.use(serveStatic(PROD_INDEX_PATH, { index: false }));
  }

  app.use("/*", async (req, res, next) => {
    const shop = Shopify.Utils.sanitizeShop(req.query.shop);
    if (!shop) {
      res.status(500);
      return res.send("No shop provided");
    }

    const appInstalled = await AppInstallations.includes(shop);

    if (shop && !appInstalled) {
      res.redirect(`/api/auth?shop=${encodeURIComponent(shop)}`);
    } else {
      const fs = await import("fs");
      const fallbackFile = join(
        isProd ? PROD_INDEX_PATH : DEV_INDEX_PATH,
        "index.html"
      );
      res
        .status(200)
        .set("Content-Type", "text/html")
        .send(fs.readFileSync(fallbackFile));
    }
  });

  return { app };
}

createServer().then(({ app }) => app.listen(PORT));

Can anyone please help me with this I am new to Shopify app development? 
when I m trying to install the app I m getting this error. 
https://prnt.sc/u48ZAFczE_le

**Comment by mkevinosullivan** [comment]
@amitkumar3211 
Please describe:
1. What version of the API are you using?
1. How are you running your app? e.g., using the Shopify CLI?
1. What URL are you using to install your app?

The error from `safeCompare` will arise when a hash of a webhook query doesn't match the hmac (unlikely in this case when the app is not yet installed) or when the OAuth callback query's hmac doesn't match or the cookie value doesn't match.

**Comment by amitkumar3211** [comment]
thanks, issue was resolved I used another way for authorization
