### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Current Context.API_VERSION 'unstable' does not match resource version 2022-07

### ISSUE THREAD

**Issue by minhloc99** [Shopify/shopify-api-node#470]
# Issue summary

I am making some apis which create customCollection and products using shopify admin api. The apis are written using firebase functions and express. When I tried to create a custom collection, the error occurred. The code is below:
```
require("dotenv").config();
const functions = require("firebase-functions");
const express = require("express");
const cors = require("cors");

const { Shopify } = require("@shopify/shopify-api");
const { CustomCollection } = require('@shopify/shopify-api/dist/rest-resources/2022-07/index.js');

const session = {
  shop: process.env.SHOPIFY_STORE_NAME,
  accessToken: process.env.SHOPIFY_ADMIN_API_ACCESS_TOKEN
};

const shopifyAdminApis = new Shopify.Clients.Rest(session.shop, session.accessToken);
const app = express();

app.use(cors({ origin: true }));

app.post("/customCollections/create", async (req, res, next) => {
  const newEvent = new CustomCollection({ session });
  const { title } = req.body;

  newEvent.title = title;
  newEvent.published = false;
  await newEvent.save({ update: true });

  res.status(200).send(true);
  return next();
});
```

**The Admin API access scopes are:**
`write_product_listings, read_product_listings, write_products, read_products, write_content_entries, read_content_entries, write_content_models, read_content_models`

**Shopify npm package version:**
"@shopify/shopify-api": "^5.0.1"

## Expected behavior

I want to create customCollection and product successfully!

## Actual behavior

Error occurred: UnhandledPromiseRejectionWarning: Error: Current Context.API_VERSION 'unstable' does not match resource version 2022-07

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
@minhloc99 Your call to `Shopify.Context.initialize` is either specifying `API_VERSION: ApiVersion.Unstable` or it's not specifying `API_VERSION` at all in its parameters (in which case it defaults to `ApiVersion.Unstable`.  There are no REST resources supported for the `Unstable` API version.

Set `API_VERSION` to `ApiVersion.July22` in order to match the REST resources you are attempting to use.
