### ISSUE TITLE
Cookie Not Found [Error]: Cannot complete OAuth process on Safari 15.6.1

### ISSUE THREAD

**Issue by julien-mamalian** [Shopify/shopify-api-node#486]
# Issue summary

For some of our merchants, in Safari 15.6.1 we have an unexpected issue when going back to auth/callback. The merchants are not able to access the app anymore. We requested access to the merchants store and cannot reproduce the issue, even on the same browser.

We moved from koa-shopify-auth@3.2.0 to the last version of shopify-api package. The users did not have the issue with koa-shopify-auth@3.2.0 auth (that sent no secured cookies on Safari). 

We are using Koa / Next.js. Our app is not embedded.

Is there a way the issue is caused by cookie params differences between both packages?
Is it specific to the client Safari's config? 🤔 We added a page to request cookie consent, but it does not change anything.

We are a bit lost and we do not understand what we can miss here...

## Expected behavior

After auth, the cookie should be added to the client browser.

## Actual behavior

An error prevents the user from completing the auth process.

`CookieNotFound [Error]: Cannot complete OAuth process. `

---

## Checklist

- [X] I have described this issue in a way that is actionable (if possible)

**Comment by Lancer92** [comment]
Also have such error. Looks like for now custom session storage must also have "optional" findSessionsByShopCallback method:
> CustomSessionStorage failed to find sessions by shop. Error Details: findSessionsByShopCallback not defined.
but after I added it, it started to search for sessions in another way, so can't find them without update. It starts recursively redirect to /exitiframe, and app not loads and shows "too many redirects" error. 
When I added exception, not redirect to that path if it's already the same, I received just same error 
> CookieNotFound [Error]: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: ******.myshopify.com
It's a blocker bug!
