### ISSUE TITLE
Create dev/next tag deployments for `shopify_api_next` branch

### ISSUE THREAD

**Issue by tolgap** [Shopify/shopify-api-node#502]
## Overview/summary

I can see that there are major overhauls happening to this library. And they seem all for the best! I would really appreciate for library builders that use `@shopify/shopify-api` as a dependency to already have dev releases of this branch. So they can keep their own libraries up to pace with whatever major changes are happening.

## Motivation

> What inspired this enhancement?

I maintain a package that uses `shopify-api-node`. The incoming changes are massive. Would be nice to tackle them ahead of release of a new major breaking version.

Is it possible to setup a flow where every new commit to `shopify_api_next` branch gets pushed to NPM under a dev or next tag?

## Checklist

- [x] I have described this enhancement in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
@tolgap Thanks for raising this.

There's now a `v6.0.0-rc1` version available to experiment with, and we'll look to do so in the future when the changes between versions are similarly significant.
