### ISSUE TITLE
[Help] How to call the api (endpoints)

### ISSUE THREAD

**Issue by sriniva7** [Shopify/shopify-api-node#508]
### I want to call this below api from postman

![github_api_custom_call_issueRaise](https://user-images.githubusercontent.com/35147480/191677746-b3682ea7-8c0e-4083-8770-bca2ed5ad9b4.png)

- **And also I want to create custom API and call that custom API from Postman.**

#### Thanks in advance.

**Comment by mkevinosullivan** [comment]
As you are new to Shopify App development, I would suggest that you work through the [Create an app](https://shopify.dev/apps/getting-started/create) and [Build an example app](https://shopify.dev/apps/getting-started/build-app-example) tutorials.

In relation to the postman question, I'd suggest to enable network tracing in your browser console and look at the request sent from the browser to `/api/products/count`, then replicate that request in postman, including the session value.

This issues list is for issues/bugs or feature requests related to the Shopify API Node, not for general development guidance.  Please refer to the developer resource website https://shopify.dev and leverage the Shopify Partner and Developer Community at https://community.shopify.com/c/partners-and-developers/ct-p/appdev
