### ISSUE TITLE
Option for trial days for billing

### ISSUE THREAD

**Issue by jakobbouchard** [Shopify/shopify-api-node#542]
## Overview

Now that billing is officially in the API, it would be nice to have a way to specify a number of days for a free trial. I am able to make a PR if necessary.

## Type

- [ ] New feature
- [x] Changes to existing features

## Motivation

When the feature wasn't in the API, it was easy to add it to the GraphQL request manually, which is what I had done, but now it's basically impossible. I suggest adding a `trialDays` parameter to plans that we create.

---

## Checklist

- [x] I have described this feature request in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
@jakobbouchard This is coming in `v6` of the API (see https://github.com/Shopify/shopify-api-node/blob/shopify_api_next/docs/usage/billing.md) ... a release candidate (currently `v6.0.0-rc4`) is available if you want to try it out in advance.

**Comment by jakobbouchard** [comment]
Oh thanks! I'll be migrating the app now, it's not published yet anyways, so not much to break haha
