### ISSUE TITLE
shopify-app-express Repo is not public!

### ISSUE THREAD

**Issue by deldrid1** [Shopify/shopify-api-node#590]
@paulomarg - sorry to report this here, but any chance you could update the permissions for @shopify/shopify-app-express?

https://github.com/Shopify/shopify-app-express/tree/main/src/session-storage looks like this for me :)

<img width="868" alt="image" src="https://user-images.githubusercontent.com/583660/200625244-2f5aeeb1-0ae1-40b2-8d3f-1f65d2a24eab.png">

**Comment by tolgap** [comment]
I was just going through the changes for from `rc1` to `rc9`. And this is a major blocker right now.

No idea how you're expected to handle session storage as of right now.

**Comment by paulomarg** [comment]
Hey folks, we were waiting until closer to release to make the repo public as it was shifting around quite a bit, but it's just been made public! We're still working on updating it to `rc9` but will have a new RC for it out soon.

Thanks again for adopting the RCs early, we really appreciate all the feedback!
